---
name: build pandoc-thesis

"on":
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - apko/pandoc-thesis.yaml

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  apko:
    name: build pandoc-thesis
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - name: checkout project
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - name: setup qemu
        uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18
      - name: apko snapshot
        id: apko
        uses: chainguard-images/actions/apko-snapshot@main
        with:
          config: apko/pandoc-thesis.yaml
          base-tag: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          target-tag: devel
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}
          archs: x86_64,aarch64
      - name: smoke test
        run: |
          set -x
          OCI=${{ steps.apko.outputs.digest }} make container
          make example
      - name: upload example
        uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb
        with:
          name: pandoc-thesis
          path: example.pdf
          if-no-files-found: error
          retention-days: 31
      - name: scan vulns
        uses: chainguard-images/actions/vul-scans@main
        with:
          image: ${{ steps.apko.outputs.digest }}
          RUN_SNYK: 'false'
          DOCKER_LOGIN: 'false'
      # tag latest only after tests and
      # after attach sbom, signature, attestation
      - name: tag pandoc-thesis (latest)
        run: |
          set -x
          crane tag "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:devel" latest
