---
name: e2e

"on":
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 0'

permissions: {}

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  OICD: https://token.actions.githubusercontent.com
  ID: https://github.com/${{ github.repository }}/.github/workflows/build.yml@refs/heads/master

jobs:
  e2e:
    name: e2e
    runs-on: ubuntu-latest
    steps:
      - name: install cosign
        uses: sigstore/cosign-installer@204a51a57a74d190b284a0ce69b44bc37201f343
      - name: verify sign
        run: |
          set -x
          cosign verify \
            --certificate-identity "${{ env.ID}}" \
            --certificate-oidc-issuer "${{ env.OICD }}" \
            "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest" | jq .
      - name: verify vuln
        run: |
          set -x
          cosign verify-attestation \
            --certificate-identity "${{ env.ID}}" \
            --certificate-oidc-issuer "${{ env.OICD }}" \
            --type vuln \
            "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest" \
            | jq -r .payload | base64 -d | jq .
